### ISSUE TITLE
[Bug]:  InternetBlock Module ERROR! FILE NOT FOUND!

### ISSUE THREAD

**Issue by CheemCow** [eaaasun/CCStopper#67]
### What happened?

Whenever I have CCStopper Running and do options 2, then 1, I get this error and I honestly have no idea what could be causing it. I allowed CCStopper in outbound rules but there isn't anything for it in inbound rules so I don't know if that's supposed to be how it is within windows firewall. I am running the batch file as an admin and I have creative cloud already installed along with a few adobe apps. I did try to see if it would still work but it just prompts me to start my free trial.

![image_2023-04-12_184058421](https://user-images.githubusercontent.com/130621047/231624184-3ea82537-29cf-484f-a95b-12f7ca90f3db.png)

### Expected Result?

I'd like to figure out why it won't work and how to make it so it is allowed to work properly.

### Version?

v1.2.2

### Windows Version?

Win 11

**Comment by eaaasun** [comment]
Hello, the official CCStopper release does not have an `Internet Block` module (not after `v1.2.0_pre.1`). You may be using a fork/alternate distribution of CCStopper. Unfortunately, I cannot provide support for those.

I recommend you get the [latest release](https://github.com/eaaasun/CCStopper/releases/latest). The internet block module was split into the `firewall block` and `add to hosts` modules, so I would recommend you try those instead.

**Comment by CheemCow** [comment]
The version I downloaded was directly from this github page. I even downloaded it multiple times and tried moving it to from different drives to see if it had to be on the same one as my creative cloud application. I did get rid of the issue by using the version prior to the one you mentioned where internet block was removed. It says 7 day trial so I'm not sure if it'll work past those 7 days but I did use the CCStopper v1.2.2 file from this github page.

**Comment by eaaasun** [comment]
Ah you are correct lol, sorry for the confusion!
can't believe I completely missed that, the message means that the three files it looks for when blocking are missing.

Please check that these files exist:
`[...]ProgramFiles(x86)\Common Files\Adobe\Adobe Desktop Common\ADS\Adobe Desktop Service.exe`
`[...]ProgramFiles\Common Files\Adobe\Adobe Desktop Common\NGL\adobe_licensing_wf.exe`
`[...]ProgramFiles\Common Files\Adobe\Adobe Desktop Common\NGL\adobe_licensing_wf_helper.exe`

Also, the old version's internet block module adds a bunch of entries to the hosts file in addition to the firewall, and so that might be what solved your issue.

**Comment by eggylot** [comment]
> 

Other versions wont work as well, but as you mentioned among those three files, the two:
[...]ProgramFiles\Common Files\Adobe\Adobe Desktop Common\NGL\adobe_licensing_wf.exe
[...]ProgramFiles\Common Files\Adobe\Adobe Desktop Common\NGL\adobe_licensing_wf_helper.exe
are missing.

**Comment by eaaasun** [comment]
With the new v1.2.3-pre.2 update, I've removed the firewall block module because the CC App patch module solves the same problem. I'll be closing this issue when v1.2.3 is stable.
